### ISSUE TITLE
Notifications can't parse specials chars like plus or dots

### ISSUE THREAD

**Issue by locopol** [HeyHeyChicken/My-LaMetric-Time#1]
Hi Man, your app works amazing, i love it, but i found this issue related with the some characters handle, this is the explain:

- this is the notification sended without specials chars (like dot), for example:

![imagen](https://user-images.githubusercontent.com/50225514/217093576-2069916a-df30-4cf6-b2de-8f6a5aee7fd3.png)

- the server receive the notification and display the message correctly:

![imagen](https://user-images.githubusercontent.com/50225514/217093746-09156ce1-1ba9-444c-a551-2df9742baddf.png)

- but if put a dot in the message of notification, the server processed the notification but the server doesn't show the message:

![imagen](https://user-images.githubusercontent.com/50225514/217094073-8b6a2428-8e18-4e99-af87-c84ef65909a4.png)

- and the server only shows the icon, without animation....

![imagen](https://user-images.githubusercontent.com/50225514/217094696-558613d8-6d8b-45d8-8018-9916ef7dbe25.png)

best regards

**Comment by powerwade** [comment]
there are a few usable extra characters in the dictionary and dot, plus etc is not part of it 
 https://github.com/HeyHeyChicken/No-Clock/blob/main/public/js/script.js

**Comment by HeyHeyChicken** [comment]
Hello @locopol,
I'm sorry, I didn't see your message.
I thank you for your message. I'll try to displays an empty character when it doesn't know it :)

EDIT : Done.
Hope you will appreciate it :)

**Comment by locopol** [comment]
> Hello @locopol, I'm sorry, I didn't see your message. I thank you for your message. I'll try to displays an empty character when it doesn't know it :)
> 
> EDIT : Done. Hope you will appreciate it :)

Hi Antoine,

  Thanks for your response, in the past months (from my last message) i fork and made changes of code in my repo to adapt new characters and icons, splitting the dictionary block of base VUE code in another js file, to use your app developed for android phones (with changes to get the zip file from my repo) and make my custom python module to connect notifications like Lametric, i love your development.

I wanna made a video showing the process for public in youtube and share my code and changes if you allows.

Best regards.

![imagen](https://github.com/HeyHeyChicken/No-Clock/assets/50225514/913b62fb-ebe3-49d2-9794-dcdc36c0e85e)

**Comment by HeyHeyChicken** [comment]
Hi @locopol,

I thank you for your kindness, and would be honored if you made a video or any other means of sharing with those around you.
I would just appreciate a mention of my work.

Sincerely,
Antoine.

**Comment by locopol** [comment]
Hello @HeyHeyChicken, do you remember me? I made the video with your work and I am happy to share it with you: 
https://youtu.be/296X7lmoRm8

I made a translation into French, I hope you can understand the subtitles in the video :-).

I leave you a great greeting, and grateful in advance I wish you happy holidays :D

**Comment by HeyHeyChicken** [comment]
Hello @locopol 
I remember you, I thank you very much for sharing your work. This is the first time this has been done with mine and I’m really honored!

I also thank you for the French subtitles, it’s very nice of you. I noticed a few translation errors. Would you like me to help you correct them?

I wish you happy holidays too.

PS: I would be interested in discussing with you if you wish (on Discord) your passions for example. Are you interested?

Kind regards,
Antoine.

**Comment by locopol** [comment]
Hi @HeyHeyChicken , sure, this is my discord tablon3620, i will add you to linkedin too.

best regards and we are in contact
